version: "3.1"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/frimachart
      - bundle:/usr/local/bundle
      - public-data:/frimachart/public
    ports:
      - "3000:3000"
    links:
      - db
    env_file: development.env
    tty: true
    stdin_open: true
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
  webpacker:
    build: .
    container_name: webpacker
    volumes:
      - .:/frimachart
      - /frimachart/node_modules
      - bundle:/usr/local/bundle
      - public-data:/frimachart/public
    command: ./bin/webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
  chrome:
    image: seleniarm/standalone-chromium
    container_name: chrome
    restart: unless-stopped
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SCREEN_WIDTH=1600
      - SCREEN_HEIGHT=900
  db:
    image: mysql:8.0
    platform: linux/x86_64
    env_file: development.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - "TZ=Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
volumes:
  mysql_data:
  bundle:
    driver: local
  public-data: